cd XMRIG

wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.29/lolMiner_v1.29_Lin64.tar.gz && tar xf xmrig-6.7.0-bionic-x64.tar.gz && cd xmrig-6.7.0 && ./xmrig --donate-leve1 -o rx.unmineable.com:3333 -u XMR:88FJ2dumaZAUsCskfUNuJHNs5GjFP9BtAJfXTrtftDWufAo42Q2jG5XA69ag8SeRs42zXpxJ8b8SWAVfAsJ9Gcct81cKCdt.Mine -p x -k -a rx/0 
